### PR TITLE
Updated excel file and added SQL file. 

### PR DESCRIPTION
**Pull request by ShridharAware**
1. Identified and corrected datatypes for columns in each table along with the constraints.
2. Made SQL file to create tables with relations among themselves.

### CODE REVIEW

**Comment by sagarbarge** [comment]
I checked your code, Please give Primary key to all tables except (movie, names)

**Comment by ShridharAware** [comment]
> I checked your code, Please give Primary key to all tables except (movie, names)

Actually, I have explored data in the excel file and identified that the correct approach to define the schema is that primary keys should be "id" from "movies" table and "id" from "names" table. In other tables references of these two primary keys should be provided like I did in SQL file.
Schema + ERD

**Comment by sagarbarge** [comment]
Great !! 😀.. Could you check my file also? where I added all foreign keys to all required tables. I think my approach is working fine, because I have added one table data (genre). And it working fine. Please check once, so we can move forward with the right approach.

**Comment by ShridharAware** [comment]
> Great !! 😀.. Could you check my file also? where I added all foreign keys to all required tables. I think my approach is working fine, because I have added one table data (genre). And it working fine. Please check once, so we can move forward with the right approach.

Yes I have reviewed your SQL file. There are some issues. We will discuss it in meeting tomarrow.

**Pull request merged**
